///////////////////////////////////////////////////////////////////////////////
// UltraFiltracjaInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "UltraFiltracjaServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
