///////////////////////////////////////////////////////////////////////////////
// UltraFiltracjaServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_UltraFiltracja = 0x3F000000;
#define SRVNAME_ULTRAFILTRACJA "UltraFiltracja"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_UltraFiltracjaCUltraFiltracjaModule = {0x36a3a3fb,0x6b67,0x4c43,{0xba,0x33,0x9a,0x21,0x37,0x87,0x37,0x85}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_UltraFiltracjaModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _UltraFiltracjaModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} UltraFiltracjaModuleParameter, *PUltraFiltracjaModuleParameter;

typedef struct _UltraFiltracjaModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} UltraFiltracjaModuleInputs, *PUltraFiltracjaModuleInputs;

typedef struct _UltraFiltracjaModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} UltraFiltracjaModuleOutputs, *PUltraFiltracjaModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_UltraFiltracjaModuleInputs 0
#define ADI_UltraFiltracjaModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
