///////////////////////////////////////////////////////////////////////////////
// PodgrzewaczServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Podgrzewacz = 0x3F000000;
#define SRVNAME_PODGRZEWACZ "Podgrzewacz"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_PodgrzewaczCPodgrzewaczModule = {0xceff06e7,0x049c,0x4de3,{0x92,0xee,0x33,0x9d,0xd5,0xaf,0xd7,0xd5}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_PodgrzewaczModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _PodgrzewaczModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} PodgrzewaczModuleParameter, *PPodgrzewaczModuleParameter;

typedef struct _PodgrzewaczModuleOutputs
{
	bool _20GKQ01AA101;
	bool _20GKQ01AA102;
	SHORT _20GKQ01AA250;
} PodgrzewaczModuleOutputs, *PPodgrzewaczModuleOutputs;

#pragma pack(push,1)
typedef struct _PodgrzewaczModuleInputs
{
	SHORT _20GKQ01CT201;
	SHORT _20GKQ01CT202;
	bool _20GBB01CF201_IMP;
	SHORT _20GBB01CF201_m3;
} PodgrzewaczModuleInputs, *PPodgrzewaczModuleInputs;
#pragma pack(pop)

typedef struct _PodgrzewaczModuleDataToOPC
{
	SHORT NR_KROKU;
	SHORT AKTUALNY_CZAS_SCHLADZANIA;
} PodgrzewaczModuleDataToOPC, *PPodgrzewaczModuleDataToOPC;

typedef struct _PodgrzewaczModuleDataFromOPC
{
	SHORT MAKS_TEMP_WODY;
	SHORT MAKS_CZAS_SCHLADZANIA;
	SHORT ZAL_FAZY;
} PodgrzewaczModuleDataFromOPC, *PPodgrzewaczModuleDataFromOPC;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_PodgrzewaczModuleOutputs 0
#define ADI_PodgrzewaczModuleInputs 1
#define ADI_PodgrzewaczModuleDataToOPC 3
#define ADI_PodgrzewaczModuleDataFromOPC 4
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
