///////////////////////////////////////////////////////////////////////////////
// PodgrzewaczClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "PodgrzewaczClassFactory.h"
#include "PodgrzewaczServices.h"
#include "PodgrzewaczVersion.h"
#include "PodgrzewaczModule.h"

BEGIN_CLASS_MAP(CPodgrzewaczClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_PodgrzewaczCPodgrzewaczModule, SRVNAME_PODGRZEWACZ "!CPodgrzewaczModule", CPodgrzewaczModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CPodgrzewaczClassFactory::CPodgrzewaczClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_PODGRZEWACZ)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Podgrzewacz));
#endif //defined(TCDBG_UNIT_VERSION)
}

