///////////////////////////////////////////////////////////////////////////////
// PodgrzewaczInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "PodgrzewaczServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
